### Inicialização ###

In [3]:
from pysus.online_data.SIA import SIA
import pandas as pd

In [4]:
sia = SIA().load()
sia

SIA - Sistema de Informações Ambulatoriais

In [5]:
sia.groups

{'AB': 'APAC de Cirurgia Bariátrica',
 'ABO': 'APAC de Acompanhamento Pós Cirurgia Bariátrica',
 'ACF': 'APAC de Confecção de Fístula',
 'AD': 'APAC de Laudos Diversos',
 'AM': 'APAC de Medicamentos',
 'AMP': 'APAC de Acompanhamento Multiprofissional',
 'AN': 'APAC de Nefrologia',
 'AQ': 'APAC de Quimioterapia',
 'AR': 'APAC de Radioterapia',
 'ATD': 'APAC de Tratamento Dialítico',
 'BI': 'Boletim de Produção Ambulatorial individualizado',
 'IMPBO': '',
 'PA': 'Produção Ambulatorial',
 'PAM': '',
 'PAR': '',
 'PAS': '',
 'PS': 'RAAS Psicossocial',
 'SAD': 'RAAS de Atenção Domiciliar'}

In [22]:
arquivo = sia.download(sia.get_files(group="PA", uf="PB", year=2026)[0])

58769400it [00:00, 1610047939.55it/s]

In [35]:
from datetime import datetime
arquivos = sia.get_files(group="PA", uf="PB", year=datetime.now().year)
arquivos

[PAPB2601.dbc, PAPB2602.dbc]

In [ ]:
mes_atual = datetime.now().month
mes_atual_arquivos = int(sia.get_files(group="PA", uf="PB", year=2026)[-1].name[-2:])
lista_meses = [n for n in range(1, 13)]
mes_esperado = lista_meses[(mes_atual-1)-2]

if mes_esperado == mes_atual_arquivos:
    print(f"Deu certo, mes atual é {mes_atual} mes do arquivo é {mes_atual_arquivos} e é igual o mês esperado que é {mes_esperado}")
else:
    print(f"Deu errado, mes atual é {mes_atual} mes do arquivo é {mes_atual_arquivos} e é diferente o mês esperado que é {mes_esperado}")

Deu certo, mes atual é 4 mes do arquivo é 2 e é igual o mês esperado que é 2

3

In [5]:
df = arquivo.to_dataframe()

In [6]:
df.head()

,PA_CODUNI,PA_GESTAO,PA_CONDIC,PA_UFMUN,PA_REGCT,PA_INCOUT,PA_INCURG,PA_TPUPS,PA_TIPPRE,PA_MN_IND,...,PA_FLQT,PA_FLER,PA_ETNIA,PA_VL_CF,PA_VL_CL,PA_VL_INC,PA_SRV_C,PA_INE,PA_NAT_JUR,PA_FNTORC
0,2707519,250750,PG,250750,0000,0000,0000,05,00,I,...,K,0,,0.00,0.00,0.00,145002,,3999,
1,2399717,250000,EP,250750,7101,0000,0000,07,00,M,...,K,0,,0.00,0.00,0.00,145002,,1023,
2,2603802,250000,EP,250630,0000,0000,0000,05,00,M,...,K,0,,0.00,0.00,0.00,,,1023,
3,2363135,250400,PG,250400,0000,0000,0000,39,00,I,...,K,0,,0.00,0.00,0.00,145001,,2062,
4,0806846,250750,PG,250750,0000,0000,0000,36,00,M,...,K,0,,0.00,0.00,0.00,,,1031,

In [7]:
df.columns

Index(['PA_CODUNI', 'PA_GESTAO', 'PA_CONDIC', 'PA_UFMUN', 'PA_REGCT',
       'PA_INCOUT', 'PA_INCURG', 'PA_TPUPS', 'PA_TIPPRE', 'PA_MN_IND',
       'PA_CNPJCPF', 'PA_CNPJMNT', 'PA_CNPJ_CC', 'PA_MVM', 'PA_CMP',
       'PA_PROC_ID', 'PA_TPFIN', 'PA_SUBFIN', 'PA_NIVCPL', 'PA_DOCORIG',
       'PA_AUTORIZ', 'PA_CNSMED', 'PA_CBOCOD', 'PA_MOTSAI', 'PA_OBITO',
       'PA_ENCERR', 'PA_PERMAN', 'PA_ALTA', 'PA_TRANSF', 'PA_CIDPRI',
       'PA_CIDSEC', 'PA_CIDCAS', 'PA_CATEND', 'PA_IDADE', 'IDADEMIN',
       'IDADEMAX', 'PA_FLIDADE', 'PA_SEXO', 'PA_RACACOR', 'PA_MUNPCN',
       'PA_QTDPRO', 'PA_QTDAPR', 'PA_VALPRO', 'PA_VALAPR', 'PA_UFDIF',
       'PA_MNDIF', 'PA_DIF_VAL', 'NU_VPA_TOT', 'NU_PA_TOT', 'PA_INDICA',
       'PA_CODOCO', 'PA_FLQT', 'PA_FLER', 'PA_ETNIA', 'PA_VL_CF', 'PA_VL_CL',
       'PA_VL_INC', 'PA_SRV_C', 'PA_INE', 'PA_NAT_JUR', 'PA_FNTORC'],
      dtype='object')

### Dicionários ###

##### Dicionário para renomear colunas #####

In [ ]:

""" Tab_win - > Tabela DataSUS
    Frequecia  = PA_QTDAPR
    Quantidade Apresentada = PA_QTDPRO
    Valor Aprovada = PA_VALAPR
    Valor Apresentada = PA_VALPRO
    Valor Complemento Federal = PA_VL_CF
    Valor Complemento Local = PA_VL_CL
    Valor Incrmento = PA_VL_INC
    Municipio Atendimento  = PA_UFMUN
    CNES =  PA_CODUNI

"""

In [ ]:
mapa_colunas = {
    "PA_QTDAPR" : "frequencia",
    "PA_QTDPRO" : "quantidade_apresentada",
    "PA_VALAPR" : "valor_aprovado",
    "PA_VALPRO" : "valor_apresentado",
    "PA_UFMUN" : "municipio_atendido",
    "PA_MUNPCN" : "municipio_residencia",
    "PA_MVM" : "data",
    "PA_RACACOR" : "raca_cor",
    "PA_IDADE" : "idade",
    "PA_CODUNI" : "cnes",
    "PA_CBOCOD" : "codigo_brasileiro_ocupacao",
    "PA_PROC_ID" : "codigo_procedimento"
}

In [ ]:
df = df.rename(columns=mapa_colunas)

##### Dicionário para renomear unidades #####

In [ ]:
mapa_unidades = {
    "2597349": "AMBULATORIO DE ESPECIALIDADES AME",
    "7176295": "BASE DESCENTRALIZADA DE MAMANGUAPE SAMU 192 USB",
    "7654553": "CAPS AD III REGIONAL VALE DO MAMANGUAPE",
    "5427207": "CAPS INFANTO JUVENIL REGIONAL DO VALE DO MAMANGUAPE",
    "5489822": "CENTRAL DE REGULACAO MUNICIPAL MAMANGUAPE PB",
    "3769593": "CENTRO DE ATENCAO PSICOSSOCIAL DE MAMANGUAPE CAPS II",
    "0840386": "CENTRO DE FISIOTERAPIA MUNICIPAL",
    "2932709": "CENTRO DE IMAGENS DR ANTONIO RODRIGUES PESSOA",
    "5906822": "EQUIPE COMISSAO DE PELE DE MAMANGUAPE",
    "8095973": "LABORATORIO MUNICIPAL DE ANALISES CLINICAS DE MAMANGUAPE",
    "8077576": "MOTOLANCIA 01",
    "8077584": "MOTOLANCIA 02",
    "2871467": "PRONTO ATENDIMENTO DE MAMANGUAPE",
    "7173814": "SAMU 192 USA",
    "6389082": "SECRETARIA MUNICIPAL DE SAUDE DE MAMANGUAPE",
    "0617342": "SERVICO DE REMOCAO MUNICIPAL"
}

In [ ]:
df["nome_unidade"] = df["PA_CODUNI"].map(mapa_unidades)

##### Dicionário para renomear Municípios #####

In [ ]:
mapa_municipios = {
    "2500106": "Água Branca",
    "2500205": "Aguiar",
    "2500304": "Alagoa Grande",
    "2500403": "Alagoa Nova",
    "2500502": "Alagoinha",
    "2500536": "Alcantil",
    "2500577": "Algodão de Jandaíra",
    "2500601": "Alhandra",
    "2500734": "Amparo",
    "2500775": "Aparecida",
    "2500809": "Araçagi",
    "2500908": "Arara",
    "2501005": "Araruna",
    "2501104": "Areia",
    "2501153": "Areia de Baraúnas",
    "2501203": "Areial",
    "2501302": "Aroeiras",
    "2501351": "Assunção",
    "2501401": "Baía da Traição",
    "2501500": "Bananeiras",
    "2501534": "Baraúna",
    "2501609": "Barra de Santa Rosa",
    "2501575": "Barra de Santana",
    "2501708": "Barra de São Miguel",
    "2501807": "Bayeux",
    "2501906": "Belém",
    "2502003": "Belém do Brejo do Cruz",
    "2502052": "Bernardino Batista",
    "2502102": "Boa Ventura",
    "2502151": "Boa Vista",
    "2502201": "Bom Jesus",
    "2502300": "Bom Sucesso",
    "2502409": "Bonito de Santa Fé",
    "2502508": "Boqueirão",
    "2502706": "Borborema",
    "2502805": "Brejo do Cruz",
    "2502904": "Brejo dos Santos",
    "2503001": "Caaporã",
    "2503100": "Cabaceiras",
    "2503209": "Cabedelo",
    "2503308": "Cachoeira dos Índios",
    "2503407": "Cacimba de Areia",
    "2503506": "Cacimba de Dentro",
    "2503555": "Cacimbas",
    "2503605": "Caiçara",
    "2503704": "Cajazeiras",
    "2503753": "Cajazeirinhas",
    "2503803": "Caldas Brandão",
    "2503902": "Camalaú",
    "2504009": "Campina Grande",
    "2504033": "Capim",
    "2504074": "Caraúbas",
    "2504108": "Carrapateira",
    "2504157": "Casserengue",
    "2504207": "Catingueira",
    "2504306": "Catolé do Rocha",
    "2504355": "Caturité",
    "2504405": "Conceição",
    "2504504": "Condado",
    "2504603": "Conde",
    "2504702": "Congo",
    "2504801": "Coremas",
    "2504850": "Coxixola",
    "2504900": "Cruz do Espírito Santo",
    "2505006": "Cubati",
    "2505105": "Cuité",
    "2505238": "Cuité de Mamanguape",
    "2505204": "Cuitegi",
    "2505303": "Curral Velho",
    "2505279": "Curral de Cima",
    "2505352": "Damião",
    "2505402": "Desterro",
    "2505600": "Diamante",
    "2505709": "Dona Inês",
    "2505808": "Duas Estradas",
    "2505907": "Emas",
    "2506004": "Esperança",
    "2506103": "Fagundes",
    "2506202": "Frei Martinho",
    "2506251": "Gado Bravo",
    "2506301": "Guarabira",
    "2506400": "Gurinhém",
    "2506509": "Gurjão",
    "2506608": "Ibiara",
    "2502607": "Igaracy",
    "2506707": "Imaculada",
    "2506806": "Ingá",
    "2506905": "Itabaiana",
    "2507002": "Itaporanga",
    "2507101": "Itapororoca",
    "2507200": "Itatuba",
    "2507309": "Jacaraú",
    "2507408": "Jericó",
    "2507507": "João Pessoa",
    "2513653": "Joca Claudino",
    "2507606": "Juarez Távora",
    "2507705": "Juazeirinho",
    "2507804": "Junco do Seridó",
    "2507903": "Juripiranga",
    "2508000": "Juru",
    "2508109": "Lagoa",
    "2508307": "Lagoa Seca",
    "2508208": "Lagoa de Dentro",
    "2508406": "Lastro",
    "2508505": "Livramento",
    "2508554": "Logradouro",
    "2508604": "Lucena",
    "2508703": "Mãe d'Água",
    "2508802": "Malta",
    "2508901": "Mamanguape",
    "2509008": "Manaíra",
    "2509057": "Marcação",
    "2509107": "Mari",
    "2509156": "Marizópolis",
    "2509206": "Massaranduba",
    "2509305": "Mataraca",
    "2509339": "Matinhas",
    "2509370": "Mato Grosso",
    "2509396": "Maturéia",
    "2509404": "Mogeiro",
    "2509503": "Montadas",
    "2509602": "Monte Horebe",
    "2509701": "Monteiro",
    "2509800": "Mulungu",
    "2509909": "Natuba",
    "2510006": "Nazarezinho",
    "2510105": "Nova Floresta",
    "2510204": "Nova Olinda",
    "2510303": "Nova Palmeira",
    "2510402": "Olho d'Água",
    "2510501": "Olivedos",
    "2510600": "Ouro Velho",
    "2510659": "Parari",
    "2510709": "Passagem",
    "2510808": "Patos",
    "2510907": "Paulista",
    "2511004": "Pedra Branca",
    "2511103": "Pedra Lavrada",
    "2511202": "Pedras de Fogo",
    "2512721": "Pedro Régis",
    "2511301": "Piancó",
    "2511400": "Picuí",
    "2511509": "Pilar",
    "2511608": "Pilões",
    "2511707": "Pilõezinhos",
    "2511806": "Pirpirituba",
    "2511905": "Pitimbu",
    "2512002": "Pocinhos",
    "2512036": "Poço Dantas",
    "2512077": "Poço de José de Moura",
    "2512101": "Pombal",
    "2512200": "Prata",
    "2512309": "Princesa Isabel",
    "2512408": "Puxinanã",
    "2512507": "Queimadas",
    "2512606": "Quixaba",
    "2512705": "Remígio",
    "2512747": "Riachão",
    "2512754": "Riachão do Bacamarte",
    "2512762": "Riachão do Poço",
    "2512788": "Riacho de Santo Antônio",
    "2512804": "Riacho dos Cavalos",
    "2512903": "Rio Tinto",
    "2513000": "Salgadinho",
    "2513109": "Salgado de São Félix",
    "2513158": "Santa Cecília",
    "2513208": "Santa Cruz",
    "2513307": "Santa Helena",
    "2513356": "Santa Inês",
    "2513406": "Santa Luzia",
    "2513703": "Santa Rita",
    "2513802": "Santa Teresinha",
    "2513505": "Santana de Mangueira",
    "2513604": "Santana dos Garrotes",
    "2513851": "Santo André",
    "2513927": "São Bentinho",
    "2513901": "São Bento",
    "2513968": "São Domingos",
    "2513943": "São Domingos do Cariri",
    "2513984": "São Francisco",
    "2514008": "São João do Cariri",
    "2500700": "São João do Rio do Peixe",
    "2514107": "São João do Tigre",
    "2514206": "São José da Lagoa Tapada",
    "2514305": "São José de Caiana",
    "2514404": "São José de Espinharas",
    "2514503": "São José de Piranhas",
    "2514552": "São José de Princesa",
    "2514602": "São José do Bonfim",
    "2514651": "São José do Brejo do Cruz",
    "2514701": "São José do Sabugi",
    "2514800": "São José dos Cordeiros",
    "2514453": "São José dos Ramos",
    "2514909": "São Mamede",
    "2515005": "São Miguel de Taipu",
    "2515104": "São Sebastião de Lagoa de Roça",
    "2515203": "São Sebastião do Umbuzeiro",
    "2515401": "São Vicente do Seridó",
    "2515302": "Sapé",
    "2515500": "Serra Branca",
    "2515708": "Serra Grande",
    "2515807": "Serra Redonda",
    "2515609": "Serra da Raiz",
    "2515906": "Serraria",
    "2515930": "Sertãozinho",
    "2515971": "Sobrado",
    "2516003": "Solânea",
    "2516102": "Soledade",
    "2516151": "Sossêgo",
    "2516201": "Sousa",
    "2516300": "Sumé",
    "2516409": "Tacima",
    "2516508": "Taperoá",
    "2516607": "Tavares",
    "2516706": "Teixeira",
    "2516755": "Tenório",
    "2516805": "Triunfo",
    "2516904": "Uiraúna",
    "2517001": "Umbuzeiro",
    "2517100": "Várzea",
    "2517209": "Vieirópolis",
    "2505501": "Vista Serrana",
    "2517407": "Zabelê"
}

In [ ]:
df["PA_UFMUN"] = df["PA_UFMUN"].astype(str)
df["municipio"] = df["PA_UFMUN"].map(mapa_municipios)

### CODUNI ###

In [20]:
df["PA_VL_INC"] = df["PA_VL_INC"].astype(float)

sum(df["PA_VL_INC"])

314822.5400000011

In [42]:
df[df["PA_UFMUN"] == "250890"]["PA_CODUNI"].value_counts()#2597349

PA_CODUNI
7666772    27404
2597349     2279
2932709     1185
3769593     1097
5489822      991
7654553      979
5906822      253
0840386      248
3742679      218
5113229      114
2821893       65
2821907       52
2606429       47
8095973       42
2606488       36
2821885       28
2606461       27
5734460       27
2606402       20
2356856       16
2606453       16
2606496       12
2871467       11
2356848        8
7305389        6
7173814        6
7176295        5
0617342        1
Name: count, dtype: Int64

In [37]:
quantidade_aprovada = df[["PA_UFMUN", "PA_QTDAPR"]].groupby(by="PA_UFMUN").sum().reset_index()
quantidade_aprovada.columns = ["PA_UFMUN", "Frequencia"]

  PA_UFMUN  PA_VALAPR  PA_VALPRO
0   250890   95310.55    96891.9

In [39]:
quantidade_aprovada[quantidade_aprovada["PA_UFMUN"] == "250890"]

   PA_UFMUN  Frequencia
93   250890     53230.0