In [1]:
from pysus.online_data.SIA import SIA
import pandas as pd

In [2]:
sia = SIA().load()
sia

SIA - Sistema de Informações Ambulatoriais

In [3]:
sia.groups

{'AB': 'APAC de Cirurgia Bariátrica',
 'ABO': 'APAC de Acompanhamento Pós Cirurgia Bariátrica',
 'ACF': 'APAC de Confecção de Fístula',
 'AD': 'APAC de Laudos Diversos',
 'AM': 'APAC de Medicamentos',
 'AMP': 'APAC de Acompanhamento Multiprofissional',
 'AN': 'APAC de Nefrologia',
 'AQ': 'APAC de Quimioterapia',
 'AR': 'APAC de Radioterapia',
 'ATD': 'APAC de Tratamento Dialítico',
 'BI': 'Boletim de Produção Ambulatorial individualizado',
 'IMPBO': '',
 'PA': 'Produção Ambulatorial',
 'PAM': '',
 'PAR': '',
 'PAS': '',
 'PS': 'RAAS Psicossocial',
 'SAD': 'RAAS de Atenção Domiciliar'}

In [4]:
arquivo = sia.download(sia.get_files(group="PA", uf="PB", year=2026)[0])

58769400it [00:00, 8552381149.73it/s]

In [5]:
df = arquivo.to_dataframe()

In [6]:
df.head()

,PA_CODUNI,PA_GESTAO,PA_CONDIC,PA_UFMUN,PA_REGCT,PA_INCOUT,PA_INCURG,PA_TPUPS,PA_TIPPRE,PA_MN_IND,...,PA_FLQT,PA_FLER,PA_ETNIA,PA_VL_CF,PA_VL_CL,PA_VL_INC,PA_SRV_C,PA_INE,PA_NAT_JUR,PA_FNTORC
0,2707519,250750,PG,250750,0000,0000,0000,05,00,I,...,K,0,,0.00,0.00,0.00,145002,,3999,
1,2399717,250000,EP,250750,7101,0000,0000,07,00,M,...,K,0,,0.00,0.00,0.00,145002,,1023,
2,2603802,250000,EP,250630,0000,0000,0000,05,00,M,...,K,0,,0.00,0.00,0.00,,,1023,
3,2363135,250400,PG,250400,0000,0000,0000,39,00,I,...,K,0,,0.00,0.00,0.00,145001,,2062,
4,0806846,250750,PG,250750,0000,0000,0000,36,00,M,...,K,0,,0.00,0.00,0.00,,,1031,

In [7]:
df.columns

Index(['PA_CODUNI', 'PA_GESTAO', 'PA_CONDIC', 'PA_UFMUN', 'PA_REGCT',
       'PA_INCOUT', 'PA_INCURG', 'PA_TPUPS', 'PA_TIPPRE', 'PA_MN_IND',
       'PA_CNPJCPF', 'PA_CNPJMNT', 'PA_CNPJ_CC', 'PA_MVM', 'PA_CMP',
       'PA_PROC_ID', 'PA_TPFIN', 'PA_SUBFIN', 'PA_NIVCPL', 'PA_DOCORIG',
       'PA_AUTORIZ', 'PA_CNSMED', 'PA_CBOCOD', 'PA_MOTSAI', 'PA_OBITO',
       'PA_ENCERR', 'PA_PERMAN', 'PA_ALTA', 'PA_TRANSF', 'PA_CIDPRI',
       'PA_CIDSEC', 'PA_CIDCAS', 'PA_CATEND', 'PA_IDADE', 'IDADEMIN',
       'IDADEMAX', 'PA_FLIDADE', 'PA_SEXO', 'PA_RACACOR', 'PA_MUNPCN',
       'PA_QTDPRO', 'PA_QTDAPR', 'PA_VALPRO', 'PA_VALAPR', 'PA_UFDIF',
       'PA_MNDIF', 'PA_DIF_VAL', 'NU_VPA_TOT', 'NU_PA_TOT', 'PA_INDICA',
       'PA_CODOCO', 'PA_FLQT', 'PA_FLER', 'PA_ETNIA', 'PA_VL_CF', 'PA_VL_CL',
       'PA_VL_INC', 'PA_SRV_C', 'PA_INE', 'PA_NAT_JUR', 'PA_FNTORC'],
      dtype='object')

In [ ]:

""" Tab_win - > Tabela DataSUS
    Frequecia  = PA_QTDAPR
    Quantidade Apresentada = PA_QTDPRO
    Valor Aprovada = PA_VALAPR
    Valor Apresentada = PA_VALPRO
    Valor Complemento Federal = PA_VL_CF
    Valor Complemento Local = PA_VL_CL
    Valor Incrmento = PA_VL_INC
    Municipio Atendimento  = PA_UFMUN
    CNES =  PA_CODUNI

"""

In [20]:
df["PA_VL_INC"] = df["PA_VL_INC"].astype(float)

sum(df["PA_VL_INC"])

314822.5400000011

In [42]:
df[df["PA_UFMUN"] == "250890"]["PA_CODUNI"].value_counts()#2597349

PA_CODUNI
7666772    27404
2597349     2279
2932709     1185
3769593     1097
5489822      991
7654553      979
5906822      253
0840386      248
3742679      218
5113229      114
2821893       65
2821907       52
2606429       47
8095973       42
2606488       36
2821885       28
2606461       27
5734460       27
2606402       20
2356856       16
2606453       16
2606496       12
2871467       11
2356848        8
7305389        6
7173814        6
7176295        5
0617342        1
Name: count, dtype: Int64

In [37]:
quantidade_aprovada = df[["PA_UFMUN", "PA_QTDAPR"]].groupby(by="PA_UFMUN").sum().reset_index()
quantidade_aprovada.columns = ["PA_UFMUN", "Frequencia"]

  PA_UFMUN  PA_VALAPR  PA_VALPRO
0   250890   95310.55    96891.9

In [39]:
quantidade_aprovada[quantidade_aprovada["PA_UFMUN"] == "250890"]

   PA_UFMUN  Frequencia
93   250890     53230.0

### Dicionários ###

##### Dicionário para renomear colunas #####

In [ ]:
mapa_colunas = {
    "PA_VL_INC": "valor_incremento",
    "PA_UFMUN": "codigo_municipio",
    "PA_CODUNI": "codigo_unidade",
    "PA_QTDAPR": "quantidade_aprovada"
}

In [ ]:
df = df.rename(columns=mapa_colunas)

##### Dicionário para renomear unidades #####

In [ ]:
mapa_unidades = {
    "2597349": "AMBULATORIO DE ESPECIALIDADES AME",
    "7176295": "BASE DESCENTRALIZADA DE MAMANGUAPE SAMU 192 USB",
    "7654553": "CAPS AD III REGIONAL VALE DO MAMANGUAPE",
    "5427207": "CAPS INFANTO JUVENIL REGIONAL DO VALE DO MAMANGUAPE",
    "5489822": "CENTRAL DE REGULACAO MUNICIPAL MAMANGUAPE PB",
    "3769593": "CENTRO DE ATENCAO PSICOSSOCIAL DE MAMANGUAPE CAPS II",
    "0840386": "CENTRO DE FISIOTERAPIA MUNICIPAL",
    "2932709": "CENTRO DE IMAGENS DR ANTONIO RODRIGUES PESSOA",
    "5906822": "EQUIPE COMISSAO DE PELE DE MAMANGUAPE",
    "8095973": "LABORATORIO MUNICIPAL DE ANALISES CLINICAS DE MAMANGUAPE",
    "8077576": "MOTOLANCIA 01",
    "8077584": "MOTOLANCIA 02",
    "2871467": "PRONTO ATENDIMENTO DE MAMANGUAPE",
    "7173814": "SAMU 192 USA",
    "6389082": "SECRETARIA MUNICIPAL DE SAUDE DE MAMANGUAPE",
    "0617342": "SERVICO DE REMOCAO MUNICIPAL"
}

In [ ]:
df["nome_unidade"] = df["PA_CODUNI"].map(mapa_unidades)